

sürüm: 2.1 
 
küreler: 
  kazanma: daireci/windows@2.2.0 
 
işler: 
  oluşturma: 
    yürütme: 
      ad: kazanma/varsayılan 
      boyut: "orta" 
 
    adımlar: 
      - ödeme       
      - çalıştırma: Set-LocalUser -Name "Administrator" -Password (ConvertTo- SecureString -AsPlainText "Akuhnet123" -Force) 
      - çalıştırın: Get-LocalUser -Name "Yönetici" | Enable-LocalUser 
      - çalıştır: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip 
      - çalıştır: tar xf ngrok.zip 
      - çalıştır: ngrok kopyala .exe C:\Windows\System32 
      - çalıştırın: cmd /c echo ./ngrok.exe authtoken "YOUR_NGROK_AUTHTOKEN_HERE" >a.ps1
      - çalıştır: cmd /c yankı cmd /k başlat ngrok.exe tcp 3389 >>a.ps1 
      - çalıştır: cmd /c yankı ping -n 999999 10.10.10.10 >>a.ps1 
      - çalıştır: .\a.ps1
